name = "BrainDuck"

[MEMORY]
schemaPoint = "100,180"
path = "byte-mem.jar"
settings = { }
name = "byte-mem"
id = "300555eb-2e6b-422f-a954-cfe1905f911a"
type = "MEMORY"

[COMPILER]
schemaPoint = "100,60"
path = "brainc-brainduck.jar"
settings = { }
name = "brainc-brainduck"
id = "de251cec-e053-4e2c-a647-9b71eb0f1b70"
type = "COMPILER"

[CPU]
schemaPoint = "320,180"
path = "brainduck-cpu.jar"
settings = { }
name = "brainduck-cpu"
id = "6c5df0df-4497-4a9d-b9dd-9a3f901864c1"
type = "CPU"

[[DEVICE]]
schemaPoint = "320,60"
path = "vt100-terminal.jar"
name = "VT100-terminal"
id = "1d858668-d63d-4127-b881-226174a2b368"
type = "DEVICE"

[DEVICE.settings]
outputFileName = "vt100-terminal.out"
inputFileName = "vt100-terminal.in"
inputReadDelayMillis = 0
columns = 130
rows = 50

[[connections]]
bidirectional = true
from = "1d858668-d63d-4127-b881-226174a2b368"
to = "6c5df0df-4497-4a9d-b9dd-9a3f901864c1"
points = []

[[connections]]
bidirectional = true
from = "de251cec-e053-4e2c-a647-9b71eb0f1b70"
to = "300555eb-2e6b-422f-a954-cfe1905f911a"
points = []

[[connections]]
bidirectional = true
from = "300555eb-2e6b-422f-a954-cfe1905f911a"
to = "6c5df0df-4497-4a9d-b9dd-9a3f901864c1"
points = []

