name = "BrainDuck"

[MEMORY]
	schemaPoint = "100,180"
	path = "brainduck-mem.jar"
	name = "brainduck-mem"
	id = "95e3a458-1d0f-40aa-9c38-f9efc5026738"
	type = "MEMORY"

[COMPILER]
	schemaPoint = "100,60"
	path = "brainc-brainduck.jar"
	name = "brainc-brainduck"
	id = "de251cec-e053-4e2c-a647-9b71eb0f1b70"
	type = "COMPILER"

[CPU]
	schemaPoint = "260,180"
	path = "brainduck-cpu.jar"
	name = "brainduck-cpu"
	id = "6c5df0df-4497-4a9d-b9dd-9a3f901864c1"
	type = "CPU"

[[DEVICE]]
	schemaPoint = "260,60"
	path = "brainduck-terminal.jar"
	name = "brainduck-terminal"
	id = "1d858668-d63d-4127-b881-226174a2b368"
	type = "DEVICE"

[[connections]]
	bidirectional = true
	from = "de251cec-e053-4e2c-a647-9b71eb0f1b70"
	to = "95e3a458-1d0f-40aa-9c38-f9efc5026738"
	points = []

[[connections]]
	bidirectional = true
	from = "95e3a458-1d0f-40aa-9c38-f9efc5026738"
	to = "6c5df0df-4497-4a9d-b9dd-9a3f901864c1"
	points = []

[[connections]]
	bidirectional = true
	from = "1d858668-d63d-4127-b881-226174a2b368"
	to = "6c5df0df-4497-4a9d-b9dd-9a3f901864c1"
	points = []

