name = "Random-Access Stored Program (RASP)"

[MEMORY]
schemaPoint = "80,180"
path = "rasp-mem.jar"
name = "rasp-mem"
id = "e0de33c4-3547-4f1b-ae1f-9b7fad88bce2"
type = "MEMORY"

[COMPILER]
schemaPoint = "80,60"
path = "raspc-rasp.jar"
name = "raspc-rasp"
id = "20f5dc7e-e72b-4bbc-ab7a-3290a78a6f86"
type = "COMPILER"

[CPU]
schemaPoint = "220,180"
path = "rasp-cpu.jar"
name = "rasp-cpu"
id = "f6e16d46-1c77-4ac9-9029-1a8652bc0f68"
type = "CPU"

[[DEVICE]]
schemaPoint = "220,60"
path = "abstract-tape.jar"
name = "abstract-tape"
id = "d3ddf28a-b865-41af-986f-bd1b2584a1bc"
type = "DEVICE"

[[DEVICE]]
schemaPoint = "380,180"
path = "abstract-tape.jar"
name = "abstract-tape"
id = "c6bbc8b5-fed7-4940-8d08-fb5ecd3f41bc"
type = "DEVICE"

[[connections]]
bidirectional = true
from = "20f5dc7e-e72b-4bbc-ab7a-3290a78a6f86"
to = "e0de33c4-3547-4f1b-ae1f-9b7fad88bce2"
points = []

[[connections]]
bidirectional = true
from = "e0de33c4-3547-4f1b-ae1f-9b7fad88bce2"
to = "f6e16d46-1c77-4ac9-9029-1a8652bc0f68"
points = []

[[connections]]
bidirectional = true
from = "d3ddf28a-b865-41af-986f-bd1b2584a1bc"
to = "f6e16d46-1c77-4ac9-9029-1a8652bc0f68"
points = []

[[connections]]
bidirectional = true
from = "c6bbc8b5-fed7-4940-8d08-fb5ecd3f41bc"
to = "f6e16d46-1c77-4ac9-9029-1a8652bc0f68"
points = []

